food_places_ee_main:
    pattern: /
    defaults: { _controller: FoodPlacesBundle:Default:index}

food_places_ee_recommended:
    pattern: /rekomenduojama/
    defaults: { _controller: FoodPlacesBundle:Default:index, recommended: 1}

food_places_ee_zaval:
    pattern: /greita/
    defaults: { _controller: FoodPlacesBundle:Default:index, zaval: 1}

food_change_location:
    pattern: /keisti
    defaults: { _controller: FoodPlacesBundle:Default:changeLocation }

food_places_ee_city:
    pattern:  /{city}/
    defaults: { _controller: FoodPlacesBundle:Default:indexCity, city: ~}
    requirements:
        city : "^(?!rekomenduojama|keisti).+"

food_places_ee_city_filter:
    pattern:  /{city}/{slug_filter}
    defaults: { _controller: FoodPlacesBundle:Default:indexCity, city: ~, slug_filter: ~}
    requirements:
        city : "^(?!rekomenduojama|keisti).+"
